server:
  port: 8040
spring:
  cloud:
    nacos:
      # 配置服务注册中心的地址, 启动时, 将自己的服务信息注册到注册中心
      server-addr: localhost:8848
      discovery:
        # 指定使用当前项目专属的命名空间
        namespace: ${spring.cloud.nacos.config.namespace}
  data:
    mongodb:
      uri: mongodb://localhost/wolf2w-comment